"""chat owner index

Revision ID: e62e277f79f4
Revises: 1e32bd1b06ce
Create Date: 2026-10-08 21:38:06.636391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62e277f79f4'
down_revision: Union[str, Sequence[str], None] = '1e32bd1b06ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chats_owner_interface', 'chats', ['owner_external_id', 'interface'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chats_owner_interface', table_name='chats')
    # ### end Alembic commands ###
